### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by ganjiapan** [dmlguq456/NeXt_TDNN_ASV#1]
Hello authors! When I saw your paper"NEXT-TDNN: MODERNIZING MULTI-SCALE TEMPORAL CONVOLUTION BACKBONE
FOR SPEAKER VERIFICATION", I thought it was a great job，I would like to refer to your source code, I found your github in the link given in the paper, but found it empty.

**Comment by dmlguq456** [comment]
Thank you for your comments! Although we said that the code have released in arxiv paper, we are acutally working in progress for our code and maybe going to be released in about a week. We'd appreciate if you could wait a little.

**Comment by ganjiapan** [comment]
Thank you so much! I'll refer to it when you're done.
