### ISSUE TITLE
"models" folder is missing

### ISSUE THREAD

**Issue by jihwanpark-airspeech** [dmlguq456/NeXt_TDNN_ASV#2]
I'm so grateful for the release of your project. 
However, it seems like the models folder is missing. 
I'm wondering if there is an update planned for this?

**Comment by dmlguq456** [comment]
I apologize for any inconvenience caused. We have identified that the models folder was mistakenly included in the '.gitignore', leading to its omission from the repository. We have rectified the issue and promptly added the models folder. Thank you for your understanding and cooperation.
