### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by wcqy-ye** [dmlguq456/NeXt_TDNN_ASV#3]
First of all, thank you very much for sharing your code. I would like to know if you have tried training with multiple GPUs and if it significantly affects the training results. Also, I encounter errors when running in test mode. I have only changed some paths in the configuration files, but I don't believe that is the cause. I look forward to your reply.
<img width="308" alt="企业微信截图_17085004087927" src="https://github.com/dmlguq456/NeXt_TDNN_ASV/assets/46421217/4f6ad415-4077-43fe-b802-8ca5486936ef">
<img width="705" alt="企业微信截图_17085005172831" src="https://github.com/dmlguq456/NeXt_TDNN_ASV/assets/46421217/7a76c725-f942-4989-8ceb-0de9b32eefc8">
<img width="698" alt="企业微信截图_17085008128555" src="https://github.com/dmlguq456/NeXt_TDNN_ASV/assets/46421217/f33efff6-4f91-45e8-ae26-3909578838ed">

**Comment by wcqy-ye** [comment]
I attempted to train using multiple GPUs, but encountered errors. This issue did not arise when training with a single GPU.
<img width="723" alt="企业微信截图_17085016834982" src="https://github.com/dmlguq456/NeXt_TDNN_ASV/assets/46421217/34c9f70c-bd90-4385-a3d2-b273e0d7659b">
<img width="737" alt="企业微信截图_17085018202293" src="https://github.com/dmlguq456/NeXt_TDNN_ASV/assets/46421217/9abe6e8b-c96a-4d52-9503-60e1c9e4064f">

**Comment by dmlguq456** [comment]
I apologize for the late answer. We only conducted our experiments on a single GPU. So, providing instructions for training with multiple GPUs would be inappropriate at this time. If possible, we recommend starting by reproducing the experimental results using a single GPU. Should you decide to proceed with multi-GPU training, it may require additional modifications following the guidelines provided by PyTorch Lightning. Again, we apologize for not being able to provide an answer to this.

**Comment by FiLafs** [comment]
> I attempted to train using multiple GPUs, but encountered errors. This issue did not arise when training with a single GPU. <img alt="企业微信截图_17085016834982" width="723" src="https://private-user-images.githubusercontent.com/46421217/306539943-34c9f70c-bd90-4385-a3d2-b273e0d7659b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDk0NDAsIm5iZiI6MTcxMjY0OTE0MCwicGF0aCI6Ii80NjQyMTIxNy8zMDY1Mzk5NDMtMzRjOWY3MGMtYmQ5MC00Mzg1LWEzZDItYjI3M2UwZDc2NTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA3NTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNmFmOTkxZGE3NjM1MDRkZmFmNmUxMzlkOTFjNDBmZGQ2MzZhNGNlMGMyNWMxMDNjMTNlOTEyNDA0ZmNhYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gxGguGIYvzAbyWRBDRGbsQCWpLK9EqanVu3TZ-Mmhjs"> <img alt="企业微信截图_17085018202293" width="737" src="https://private-user-images.githubusercontent.com/46421217/306540334-9abe6e8b-c96a-4d52-9503-60e1c9e4064f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDk0NDAsIm5iZiI6MTcxMjY0OTE0MCwicGF0aCI6Ii80NjQyMTIxNy8zMDY1NDAzMzQtOWFiZTZlOGItYzk2YS00ZDUyLTk1MDMtNjBlMWM5ZTQwNjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA3NTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNWZmYjhlOGMzMTk5OTYyY2VkYjg1ODgzZDE0MzYwN2IyYjJjMzI1OTBkODVlYmIzOGM3MGJjNzA3MTQxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6GEDzPz_jFdhtpLDj1hQoxhMKK4wFwqm1HgpC4AlTQ4">

I also encountered the same problem, have you solved it now?
